### ISSUE TITLE
Cross compile with the full Scala version

### ISSUE THREAD

**Issue by dragos** [typelevel/kind-projector#15]
I wonder why kind-projector is cross compiled using only the major Scala version. AFAIK compiler plugins can access compiler internals, therefore are not subject to any binary compatibility guarantees between (any two) releases.

**Comment by non** [comment]
Hi @dragos, sorry I only just saw this issue.

It's a good point. So far we haven't had any problems but you're right, the code could change.

I'll look into publishing against the full version.

**Comment by SethTisue** [comment]
well, lucky so far :-)

**Comment by SethTisue** [comment]
to expand on that,

we do normally recommend that compiler plugins be published against the full Scala version.

however, kind-projector is an unusual plugin, in that it runs very early during compilation. that part of the Scala compiler rarely changes.

and, using the Scala version would mean additional publishing hassle since it would have to be republished for every Scala minor version, and kind-projector is so basic in the Scala library ecosystem that any delay would be felt downstream, as well.

so on the balance, I think this is okay.

if a Scala version ever comes out that breaks the plugin, it will almost certainly cause compile-time problems (rather than expensive runtime issues), and we can rush out a new plugin version that fixes the problem.

**Comment by xuwei-k** [comment]
https://github.com/typelevel/kind-projector/issues/117

**Comment by larsrh** [comment]
Closed by #119
