### ISSUE TITLE
Multiple argument support for poly lambdas

### ISSUE THREAD

**Issue by carymrobbins** [typelevel/kind-projector#76]
Ideally, the poly λ value syntax could support multiple arguments, so instead of this -

```scala
implicit val functorOption: Functor[Option] = new Functor[Option] {
  override def map[A, B](f: A => B)(fa: Option[A]): Option[B] = fa.map(f)
}
```

we could write this -

```scala
implicit val functorOption: Functor[Option] = λ[Functor[Option]](f => fa => fa.map(f))
```

It would be even better if type inference could figure out the type arg to λ, but I have a feeling that's a baked in limitation at the moment.

```scala
implicit val functorOption: Functor[Option] = λ(f => fa => fa.map(f))

```

**Comment by TomasMikula** [comment]
At the phase the plugin runs, it is not able (nor is it its ambition) to inspect the definition of `Functor`. As a result, it is not able to infer `map`'s parameter types (`A => B`, `Option[A]`) from the expression

```scala
λ[Functor[Option]](f => fa => fa.map(f))
```

Neither does it know that the single abstract method is called `map` and that it takes two type parameters.

We could help the plugin by specifying the method name and type parameters, like this

```scala
λ[Functor[Option]].map[A, B](f => fa => fa.map(f))
```

but there's still no way to infer parameter types.

A possible solution is to define `Functor`'s `map` without any value parameters:

```scala
trait Functor[F[_]] {
  def map[A, B]: (A => B) => (F[A] => F[B])
}
```

Now we can implement rewriting

```scala
λ[Functor[Option]].map[A, B](f => fa => fa.map(f))
```

to

```scala
new Functor[Option] {
  def map[A, B] = f => fa => fa.map(f)
}
```

which is exactly what the compiler plugin [P∀scal](https://github.com/TomasMikula/pascal/) will do, except using `ν` (/njuː/) instead of `λ`.

**Comment by SethTisue** [comment]
Any objection to closing this as unlikely to progress?
